plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'mousespeed'
version = '1.0.0'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.formdev:flatlaf:3.4.1'
}

application {
    mainClass = 'MouseSpeedTracker'
}

jar {
    manifest {
        attributes 'Main-Class': 'MouseSpeedTracker'
    }
}

shadowJar {
    archiveBaseName = 'MouseSpeedTracker'
    archiveClassifier = ''
    archiveVersion = ''
}